# name: Deploy to production
# on:
#   push:
#     tags:
#       - 'v*'

# jobs:
#   Deploy-Production:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Release to production
#         run: |
#           git push origin HEAD:main -f

name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create a release
        run: |
          npx changelogen@latest gh release --token ${{ secrets.RELEASE_GH_TOKEN }}
